### ISSUE TITLE
datatypes

### ISSUE THREAD

**Issue by nadarabus** [titan550/bcpy#8]
great tool, really. However, there is problem with datatypes. I execute following code snipet:

```
table_name = 'test'
df = pd.read_csv('test1.csv') 
print(df)
print(df.dtypes)
bdf = bcpy.DataFrame(df)
sql_table = bcpy.SqlTable(sql_config, table=table_name)
bdf.to_sql(sql_table)

```
in cmd I can see there df with different datetypes:
```
(base) C:\tmp>python test.py
   col1   col2   col3
0  row1      1    1.1
1  row2      2    2.2
2  row3      3    3.3
col1      object
 col2      int64
 col3    float64
dtype: object
```

However in db there when I execute:
```
SELECT o.name AS obj_name, c.name AS col_name,  
       TYPE_NAME(c.user_type_id) AS type_name  
FROM sys.objects AS o   
JOIN sys.columns AS c  ON o.object_id = c.object_id  
WHERE o.name = 'test'  
ORDER BY col_name;  
GO  

```
I got following:

> obj_name	col_name	type_name
> test	 col2	nvarchar
> test	 col3	nvarchar
> test	col1	nvarchar
>

**Comment by mandeepsingh-private** [comment]
Agree same issue, make the utility useless.

**Comment by titan550** [comment]
My original intent was to create an eary way to perform Extract Load and then Transform (ELT) because data types in bcp are limited and barrier to entry for writing format files is high.

I acknowledge your problem with the issue of using custom format files.

Can you please make a PR with the suggested change?

**Comment by GreenMarkerr** [comment]
why is this closed?
